### ISSUE TITLE
不足要素のデザイン

### ISSUE THREAD

**Issue by fumikito** [wctokyo2017/wct2017#10]
現在のテーマにあてこんだときにまったくスタイルがあたらない部分のデザインをどうするかについて質問です。回答お願いします。

- [x] コメントフォームおよびコメント
- [x] サイドバー（現在は非表示）

**Comment by mignonstyle** [comment]
> コメントフォームおよびコメント

コメントフォームおよびコメントは表示しないので、サイトで使用しない設定にしてください。

> サイドバー

本サイト時にデザイン作りますー（ティザーサイトでは使用しない想定です）

**Comment by fumikito** [comment]
承知
