### ISSUE TITLE
メインビジュアルの大きさについて

### ISSUE THREAD

**Issue by YoshinoriKobayashi** [wctokyo2017/wct2017#13]
東京島のがメインビジュアルの大きさが気になったので書きます。

僕のMacbook Proだと画面全体に広がってちょっと圧迫感がある感じがします。そして、スクロールして次にあるのかわかりにくい感じがしました。
![macbook01](https://cloud.githubusercontent.com/assets/5963990/24615354/fcc640c8-18c8-11e7-9d97-195665f74fdc.png)

少しサイズを落としてみたのですが、このぐらいだと引き締まって綺麗に見えるなーと思います。
次の文章のタイトルも見えるので下になにかあるのがわかります。
![macbook02](https://cloud.githubusercontent.com/assets/5963990/24615521/79843b74-18c9-11e7-9782-dc9cfbe5d8fe.png)

解像度や大きなディスプレイで違ってくると思いますので、ご参考に。

**Comment by mignonstyle** [comment]
確認ありがとうございます！
ちょっと検討しますー

**Comment by mignonstyle** [comment]
@YoshinoriKobayashi 小林さんのMacbook Proの画面サイズはいくつでしょうか？
「少しサイズを落としてみた」とのことですが、「縦横pxのときにここまで入っているとよい」と具体的に教えていただけると助かります。

**Comment by YoshinoriKobayashi** [comment]
@mignonstyle　
MacBook Pro Retina 13-inch デフォルト なので、2560 x 1600 ピクセル になります！

**Comment by mignonstyle** [comment]
@YoshinoriKobayashi  「少しサイズを落としてみた」というのがどれくらいのサイズなのかよくわからないので、「ブラウザのサイズが縦横pxの場合に背景画像の幅が何pxがよい」と具体的に数値で教えていただけますか？
解像度やディスプレイで違ってくるので、数値で教えていただかないとよくわからないです。

**Comment by YoshinoriKobayashi** [comment]
@mignonstyle 
>少しサイズを落としてみた

説明が不十分でした。
ブラウザの拡大縮小のことです。Chromeで75%にしたときです。
px あとで調べておきますー。
