### ISSUE TITLE
iPhone6のSafariでみたときに、開催日がよく見えない

### ISSUE THREAD

**Issue by YoshinoriKobayashi** [wctokyo2017/wct2017#14]
iPhone6のSafariでみたときに、開催日がはっきりと認識できない感じがします。
その下の「ベールサール新宿・・・」は認識できるのですが、開催日は瞬間的にわからないので、もう少し認識できるようにしたほうがよいかも。
![img_1842](https://cloud.githubusercontent.com/assets/5963990/24616024/edb888be-18ca-11e7-9c36-1ee90cddd62e.PNG)

**Comment by mignonstyle** [comment]
確認ありがとうございます！
デザイン修正しますー
