### ISSUE TITLE
iPhoneで横にした時にサブタイトルがよく見えない。

### ISSUE THREAD

**Issue by YoshinoriKobayashi** [wctokyo2017/wct2017#15]
「JOIN」を補足する、サブタイトルの「つながる人・・・」がPCならまだ認識できるのですが、スマホだとよく見えないです。
重要な箇所なので、もう少しはっきりと認識できたほうがよいかなと思いました。

![img_1843](https://cloud.githubusercontent.com/assets/5963990/24616480/31e3ae28-18cc-11e7-99d7-37ae1fde1e8a.PNG)

**Comment by mignonstyle** [comment]
確認ありがとうございます！
デザイン修正しますー
