### ISSUE TITLE
人口衛星の配置を左からの距離ではなく、中心からの距離で配置してみる

### ISSUE THREAD

**Issue by YoshinoriKobayashi** [wctokyo2017/wct2017#16]
衛生が画面の左端から登っていますが、解像度やディスプレイサイズで横に伸びたときに、左すぎて気づかれないのでは？と思います。

画面の中心からの距離で、配置してみるとよいと思います。
その場合は衛生をどこから出してくるのか？となりますので、地平線の境界線から登ってくる感じでよいかなと思います。

中心からの配置方法は画面キャプチャか、この記事をご参考にしてください。
https://hyper-text.org/archives/2014/08/position_absolute_center_layout.shtml

![macbook03](https://cloud.githubusercontent.com/assets/5963990/24617993/8a2a0f42-18d0-11e7-833c-893684cc63f6.png)

**Comment by mignonstyle** [comment]
中心からの距離でなく、calc()とvwでウインドウサイズによって人口衛星の起点、終点を変えたらどうでしょう？フォントサイズ変えるみたいな感じで。

[font-sizeの単位をvwにしてレスポンシブ対応。Sassのmixinでわかりやすく記述する方法](http://qiita.com/katsunory/items/3bede89cee8e2ded8426)
http://qiita.com/katsunory/items/3bede89cee8e2ded8426

**Comment by inc2734** [comment]
@YoshinoriKobayashi なるほど、たしかに左端からでて400px左に移動とかになっているので大きい画面だとそうですね。ただ、今ループになっている（上までいくとまた左からでてくる）ので、地平線からでるとすると画像を切ったりがややこしそうですね…ループさせなければそのままでも良いですが。

@mignonstyle 技術的な部分は理解できますが、実際どこから動かすのかが想像できませんでした。小林さんの意見どおり画面端ではなく地平線上から、というのは採用で、あとは vw で左端になりすぎないように、という感じですかね？

**Comment by mignonstyle** [comment]
@inc2734 今はtop、leftからの位置で固定になっているので、この位置を計算させたらどうかな？と思いました。終点も同じように。
地平線上からでるのでなく、できれば画面全体の上を人工衛星が通るようにしたいですー。

![2017-04-12 9 27 05](https://cloud.githubusercontent.com/assets/7196028/24936215/50f408d4-1f62-11e7-8cbe-2413b952b6d4.png)

**Comment by inc2734** [comment]
メモ：どのウインドウサイズになっても、画面の「W」のあたり（だいたいでOK）を通るような感じにする。終点（上）も同じような感じで計算させたらだいたい同じ位置を通るようになるかも。

**Comment by mignonstyle** [comment]
@inc2734  ありがとうございます！位置はとても良いと思います！

衛星がウインドウの上まで行ったときに、画面から消えずに上のところに少し表示されたままになってしまっているのでここだけ修正お願いできますか？

![2017-04-13 16 41 26](https://cloud.githubusercontent.com/assets/7196028/24995286/4247cc50-2069-11e7-9ce7-3b8bd064ead0.png)

**Comment by inc2734** [comment]
@mignonstyle top が `$satellite-width-pc` になっていたのを `$satellite-height-pc` に変更、* -2 でも消えるようだったので * -2 にしました。

**Comment by mignonstyle** [comment]
@inc2734 ありがとうございます！こちらで大丈夫ですのでFixでお願いします！
