### ISSUE TITLE
開発環境とフレームワークの決定

### ISSUE THREAD

**Issue by fumikito** [wctokyo2017/wct2017#2]
@inc2734 @h2ham 

- 環境（VCCW, Dockerなど）
- CSSフレームワーク

上記2点を決めましょう。前提として……

- テーマは親テーマが決まっているので、マークアップは一切いじれない
- ウィジェットの中身などはいじることができる

などがあります。不明点があればコメントください。

**Comment by inc2734** [comment]
マークアップが一切いじれないのであれば、いっそ CSS フレームワークは使わないというのもアリなのではと思ったのですがどうなんでしょう？ それか Bourbon みたい mixin ライブラリとかのほうが相性良いですかねー（僕は使ったことないですが。。）

**Comment by fumikito** [comment]
@inc2734 僕もBourbon考えていて、mixin中心のやつの方がいいと思った。
ちなみに、ウィジェットの中身がいじれるっていうのは、単にテキストウィジェットで頑張る形です。
また、投稿本文にもタグを入れてがんばれますが、できても `<a href="#" class="btn">参加はこちら！</a>` ぐらいかなあと思います。
@h2ham さんはどうでしょう？

**Comment by h2ham** [comment]
@fumikito @inc2734 現時点での私の知識で、今回の制作環境で、HTMLの構成とか属性入れるとかとかで、何ができる・何ができないをまだ把握できていないのもあって、ぼんやりなイメージですが、とりあえず使わないで賛成です。  
普段CSSフレームワークとか使わずにSass書いているほうがほとんどなので、使わないでHTMLに合わせてCSS書いていくで良いと思います。

普段ライブラリも使わずに実装しているのでライブラリ利用も未知数ですが、活用できるなら使い方学ぶので、導入でも問題ないと思ってます。

**Comment by fumikito** [comment]
@inc2734 @h2ham 

mixinとグリッドフレームワークぐらいはないと僕が死んじゃうので、

- Bourbon http://bourbon.io
- Bourbon NEAT http://neat.bourbon.io

の2つを使うということでどうでしょう。

**Comment by fumikito** [comment]
では、Bourbon & NEAT で決定！
