### ISSUE TITLE
星やライトがチカチカ（キラキラ）するエフェクト

### ISSUE THREAD

**Issue by fumikito** [wctokyo2017/wct2017#4]
タイトルのエフェクトをCSSでやるときのサンプルなどあれば、リンクを貼ってください。

**Comment by inc2734** [comment]
忘れないように Slack より引用

> CSSアニメーションは少しいれてほしいです！左上の衛星が左下から右上に斜めに動くとか
> 星やライトがチカチカ（キラキラ）するとか。

**Comment by mignonstyle** [comment]
星ではないので、イメージとは違いますが、光がちかちかしてるソースを見つけたので。

光から移動まで、すべてCSSで作る光るアニメーション
http://design.kayac.com/topics/2011/12/css3.php

**Comment by inc2734** [comment]
https://codepen.io/WebSonick/pen/vjmgu

**Comment by inc2734** [comment]
ヘッダーのウィジェットの中に `<div class="header-star"></div>` を4個いれてください。

**Comment by mignonstyle** [comment]
@inc2734 ありがとうございます！星のキラキラとても良い感じです！
星の数を少し増やしたいので、ブランチ切って私のほうで続きからやりますねー。

**Comment by mignonstyle** [comment]
After Header(Home Page) ウィジェットにテキストで以下を追加してください。
（.header-star 8個、.header-star twinkl 4個）

```
<div class="header-star"></div>
<div class="header-star"></div>
<div class="header-star"></div>
<div class="header-star"></div>
<div class="header-star"></div>
<div class="header-star"></div>
<div class="header-star"></div>
<div class="header-star"></div>
<div class="header-star twinkl"></div>
<div class="header-star twinkl"></div>
<div class="header-star twinkl"></div>
<div class="header-star twinkl"></div>
```
