### ISSUE TITLE
フッターのWPロゴがただしく表示されていない

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#44]
WPロゴの表示がおかしいようなので、お手数ですがご確認お願いします！
![2017-07-22 17 26 56](https://user-images.githubusercontent.com/7196028/28489686-29d9c8d8-6f03-11e7-9978-d123b6bfc7e0.png)

**Comment by inc2734** [comment]
これもしかしたらバージョンの問題ですかねぇ。Font Awesome 自体は読み込まれていますが、`.fa-wordpress`が定義されてないようです。

**Comment by fumikito** [comment]
Tagregatorとかいうプラグインがfont-awesome3.2.1を読み込んでしまっているのが原因っぽい。
