### ISSUE TITLE
スポンサーの詳細ページ作る

### ISSUE THREAD

**Issue by fumikito** [wctokyo2017/wct2017#49]
WEBデザイン班の方へ
　表示されるロゴの位置を修正頂きたいのです。自分　テーマの編集権限ないので、ある方にお願いいただけませんか？

**Comment by mekemoke** [comment]
[![Screenshot from Gyazo](https://gyazo.com/14ed02a0b75c690a83dc31370b36d737/raw)](https://gyazo.com/14ed02a0b75c690a83dc31370b36d737)
参考の元画像を入れておきますね。
ロゴが中央揃えになるのが理想です。
