### ISSUE TITLE
トップページのチケットボタンを有効にしてください

### ISSUE THREAD

**Issue by mekemoke** [wctokyo2017/wct2017#51]
[![Screenshot from Gyazo](https://gyazo.com/59649e44d8ce217fd5f6c0bfe0e74ae0/raw)](https://gyazo.com/59649e44d8ce217fd5f6c0bfe0e74ae0)

固定ページから直そうと思ったらできなかったので、制作班の方、お願いします！

**Comment by fumikito** [comment]
しました。
