### ISSUE TITLE
スマホからだと英語の各ページへアクセスできない

### ISSUE THREAD

**Issue by waviaei** [wctokyo2017/wct2017#52]
- デスクトップの横幅でみると右上の「English」がドロップダウンメニューになっていますが、615px(?)以下になるとドロップダウンメニューとして機能しなくなる
- 加えて、「メニュー」は日本語のままで、開いても英語ページへのリンクがない

ので、スマホから英語版の各ページへアクセスできない。

**Comment by fumikito** [comment]
うーむ、サブメニューで対応しますか。

**Comment by waviaei** [comment]
去年は日本語のメニューの一番下にありましたが、それも気づかないですよね…

サブメニューというのは、もう1つメニューを英語専用で作って、Hero画像と、ページタイトルの間に横並びに表示させる…って感じのイメージでしょうか？

僕もそれくらいしか思いつかないです。

**Comment by mignonstyle** [comment]
英語版のトップページ https://2017.tokyo.wordcamp.org/en/ に、
英語の各ページへのリンク一覧を掲載してはいかがでしょうか？

サブメニュー？だとメニューの項目が増えたときに
見づらくなったりしないかな？というのが気になります。
（日本語ページでは非表示にするとしても。）

とりあえず簡単にリンク一覧ページを作ってみましたので、
操作感などお試しいただいてもよろしいでしょうか？
https://2017.tokyo.wordcamp.org/en/

使いづらいようでしたら元に戻します。
（メニューのページのタイトルは適当なので、
適したタイトルに変更していただけると助かります。）

**Comment by mignonstyle** [comment]
グローバル班のSlackで確認していただいたところ、
西川さんから「たどり着ければいいと思いますよ」とお言葉をいただいたので、
こちらはFixとさせていただきますね。

ありがとうございました。
