### ISSUE TITLE
スマホからだと、英語ページに移動しても気づかない

### ISSUE THREAD

**Issue by waviaei** [wctokyo2017/wct2017#53]
スマホからだとグローバルメニューとhero画像部分がファーストビューに表示されますが：

- メニューの"English"の色は変わらない
- 画像の中の場所を記載した部分が日本語のままで、英語に変わらない

ので一見わかりません。

https://wctokyo2017.github.io/wct2017/assets/images/wct2017-date.svg
を英語ページの場合のみ英訳したversionにreplaceするのは可能でしょうか？

**Comment by fumikito** [comment]
@inc2734 これお願いできますか？　英語の固定ページはスラッグに -en がつくので、それで対応できるかと。

**Comment by inc2734** [comment]
@fumikito @mignonstyle @waviaei つくってみましたがこんな感じでどうでしょう？
<img width="1272" alt="en" src="https://user-images.githubusercontent.com/1094306/28597115-281f6b48-71d7-11e7-8cbd-7549f979ba9e.png">

**Comment by fumikito** [comment]
@inc2734  おけです。マスターにマージの上、デプロイお願いします。

**Comment by waviaei** [comment]
@fumikito @fumikito 
ありがとうございます！確認しました！

…なのですが、場所の英語名を下記に変えていただけないでしょうか？"Sumitomo~~" は会場名ではなく、会場が入っている建物名なので…

Bellesalle Shinjuku Grand 5th Floor Conference Center

お手数をおかけしますが、急ぎではないんで、何かのついでにでもお願いします！

**Comment by mignonstyle** [comment]
@inc2734  すみません、おてすきのときでよいので、こちらお願いしますー
> 英語ページはメインビジュアルの会場名を英語に

> …なのですが、場所の英語名を下記に変えていただけないでしょうか？"Sumitomo~~" は会場名ではなく、会場が入っている建物名なので…
>
> Bellesalle Shinjuku Grand 5th Floor Conference Center
