### ISSUE TITLE
メインビジュアルにわぷーを追加してください。

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#61]
データはWCTドライブの
デザイン班 > 印刷 > わぷーに入っています。

**Comment by fumikito** [comment]
@mignonstyle @inc2734 やってみましたが、どうでしょう。

**Comment by mignonstyle** [comment]
@fumikito  ありがとうございます！確認しました。動きはそんな感じで大丈夫ですので、わぷーの大きさと位置をカンプのようにお願いできますか？

<img width="512" alt="default" src="https://user-images.githubusercontent.com/7196028/28752957-fb44ae20-7565-11e7-965a-0a2f1e3c14e2.png">

**Comment by fumikito** [comment]
@mignonstyle カンプの元ファイルが見つけられなかったので、大体で合わせました。
スマホのときのレイアウトが不明だったので、上にあいていた余白のど真ん中に浮かべています。

**Comment by mignonstyle** [comment]
@fumikito  修正ありがとうございます！

できればわぷー画像はsvgにしていただけますか？
位置などはOKですので、公開よろしくお願いいたします。
（とりあえず公開して、あとから画像差し替えでも大丈夫です）

スマホのときのレイアウトは、メインビジュアル全体的に修正しますので、
その際にまた調整などお願いするかと思いますが、よろしくお願いします
（スマホ＆下層ページデザインの作業がおいついてなくてすみません）

**Comment by fumikito** [comment]
@mignonstyle SVG化はめんどくさいので、あとでいいですか。とりあえずクローズしてください。
