### ISSUE TITLE
ブログの「続きを読む →」からページを表示したときに、本文の1行目が切れている

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#64]
サイトの「ブログ」の「続きを読む →」で投稿ページを表示すると、
https://2017.tokyo.wordcamp.org/blog/

コンテンツの1行目が切れていて、ちゃんと表示されていません。修正よろしくお願い致します。
![2017-07-29 11 44 41](https://user-images.githubusercontent.com/7196028/28741554-759fdba4-7453-11e7-93dc-1fe36b80bcbe.png)

タイトルをクリックして投稿ページを表示した場合は、ただしく表示されています。
![2017-07-29 11 47 03](https://user-images.githubusercontent.com/7196028/28741560-add842b8-7453-11e7-9b23-2bbdabc15522.png)

**Comment by fumikito** [comment]
@mignonstyle 再現できないんですけど、ブラウザなんですか？

**Comment by mignonstyle** [comment]
@fumikito  すみません、FirefoxとSafariとChromeで確認したところ、すべてで見切れてしまっているのですが・・・（WCT 2016のサイトのブログは「続きを読む →」からでも正しく表示されています）

私の環境の問題でしたら、こちらの Issues は Close にしていただいて大丈夫ですー。

**Comment by inc2734** [comment]
@fumikito @mignonstyle Mac の Chrome でみたら再現しました。変な CSS があるわけではなさそうなのでなんらかのバグかもしれません。詳しく調べられてはいませんが、`.entry-content` の `overflow: hidden` を消すと良いかもしれません（副作用がありそうな気もしますが…
