### ISSUE TITLE
スポンサー詳細ページのアイキャッチを非表示にしてください

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#65]
すみません、タイトルの下にリンク付きでスポンサーロゴを掲載しますので、スポンサー詳細ページのアイキャッチは非表示でお願いします。
https://2017.tokyo.wordcamp.org/sponsor/tarosky/

**Comment by fumikito** [comment]
すぐ対応できるかわからないのと、運用に関わること（入稿内容によっては選べなくなる）ので、現状のままにしてもらえませんか？
あまり意味のある変更に思えないですし。

**Comment by mignonstyle** [comment]
@fumikito 
デフォルトでは、スポンサー詳細ページから、スポンサーさんのサイトへのリンクがなく、WCT2016ではスポンサーのサイトへのリンクのボタンを手入力で掲載していました。

リンクボタンよりもロゴにリンクをつけていたほうが、みやすいしわかりやすいので、このように対応していただけますか？
Kyotoでもこのような表示方法になっていて、デザイン的にもすっきりして印象がよいなと思いました。
https://2017.kyoto.wordcamp.org/sponsor/jetpack/

**Comment by fumikito** [comment]
@mignonstyle こういうパターンもあるので、現状のままでいいと思うんですが、どうでしょう。

https://2017.tokyo.wordcamp.org/sponsor/gmopepabo/

**Comment by mignonstyle** [comment]
タイトルの上に表示されていた「Featured Image」が表示されていなければ大丈夫ですー。
（今みたら、タイトル上のロゴは表示されていませんでした。）

タイトルの下に表示されているロゴは、私が手入力で追加したスポンサーのサイトへのリンク付きのロゴ画像なので。
