### ISSUE TITLE
スマホでのボタンのスタイルがくずれている

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#67]
スマホで表示したときにボタンのスタイルがくずれているので修正お願いします。
PCでは問題ありません。

https://2017.tokyo.wordcamp.org/tickets/
https://2017.tokyo.wordcamp.org/media-contact/

![image_uploaded_from_ios_720](https://user-images.githubusercontent.com/7196028/28760771-759cf1ea-75e4-11e7-95b8-11a5a816262d.jpg)

**Comment by inc2734** [comment]
Android ( Chrome ) だと問題ありませんでしたが、iOS だとそうなるみたいですね。グラデーションになってるように見えますがそういう指定は無いっぽいですし…うーん

**Comment by fumikito** [comment]
iOSにwebkit-appearance的なやつがあるので、それをオフにすれば大丈夫です。
