### ISSUE TITLE
タイムテーブルのデザイン作成

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#68]
タイムテーブルのページを作りかけで申し訳ないですが、
枠組み入れていってるので、テーブルの色とかをサイトのデザインにあわせて修正お願いします。
セッション情報は8月上旬公開予定で準備中です。

https://2017.tokyo.wordcamp.org/schedule/

**Comment by mignonstyle** [comment]
@inc2734  @fumikito  とりあえずPC版は作りましたが、SP版での調整お願いできますか？
1. 空欄のセルを非表示に
2. 全部左詰め
3. 時間を枠の外に出す
4. 部屋番号を見出しに
5. 「Speader:」を非表示、もしくはアイコンフォントに

3と4は、Kyotoみたいにしていただけるとかっこいいなと思いました。

<img width="431" alt="2017-08-07 15 17 02" src="https://user-images.githubusercontent.com/7196028/29014340-82e7b552-7b83-11e7-8bd9-1215bb80c4f6.png">

**Comment by inc2734** [comment]
@mignonstyle ローカルで同じスラッグ・HTMLでタイムテーブルをつくってみたのですが本サイトのようなデザインがあたりませんでした。PCのタイムテーブルをつくりるにあたり、CSS の追加をされましたかね？もしされていて master に未反映であれば反映していただきたいです。

**Comment by mignonstyle** [comment]
@inc2734  ありがとうございます。ラベルの位置についてはちょっと考えさせてください。
お手数ですが、スマホ時に以下のセルを非表示にしていただけますか。

- 12:30 お昼休み / Lunch Time ← 2つとも
- 16:50 懇親会準備

![2017-08-08 12 24 25](https://user-images.githubusercontent.com/7196028/29055116-84de0c32-7c35-11e7-8057-c671a1ca38b1.png)

![2017-08-08 12 28 59](https://user-images.githubusercontent.com/7196028/29055122-8d0e8df0-7c35-11e7-9fd0-c62bafd7c062.png)

**Comment by mignonstyle** [comment]
@inc2734 すいません、11:00 〜 16:40 の時間の空白セルを background:none にしていただけますか？今はグレイの色がついています。
私のタグの指定の仕方がよくなくて、追加CSSをstyle.cssに移した際に、CSSの優先順位が変わってしまったかもしれないです。

![2017-08-08 13 04 06](https://user-images.githubusercontent.com/7196028/29055888-24dc2b2a-7c3a-11e7-895a-c3843d15673a.png)

![2017-08-08 15 14 19](https://user-images.githubusercontent.com/7196028/29058634-55be0af8-7c4c-11e7-89a4-0ca392c295ce.png)

**Comment by mignonstyle** [comment]
@inc2734  修正ありがとうございます！すみません、おてすきのときでよいので、
10:00 の空欄の背景色が消えてしまっているのでグレイの色をつけていただけますか？お手数おかけしますがよろしくお願い致します。

![2017-08-09 8 44 37](https://user-images.githubusercontent.com/7196028/29099274-587fed22-7cdf-11e7-9567-1d23f4137940.png)

![2017-08-09 8 44 44](https://user-images.githubusercontent.com/7196028/29099278-5bcee5f0-7cdf-11e7-9962-9018b3ef86be.png)

**Comment by inc2734** [comment]
@mignonstyle 修正しました！

**Comment by mignonstyle** [comment]
@inc2734  修正ありがとうございます！東京にきたら文樹さんに奢っていただいてください！ ← ？
