### ISSUE TITLE
スピーカー詳細ページのデザイン作成

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#69]
去年のような感じでよいので、色などは今年のデザインにあわせて作成お願いいたします。
管理画面の「スピーカー」で情報入力用のテンプレを作成していただけると助かります（去年のコピペで大丈夫です）
https://2016.tokyo.wordcamp.org/speaker/mignonstyle/

**Comment by inc2734** [comment]
現状でもそんなに変じゃないと思うのですが（色は良い感じに見えます）、2016のように投稿日時の非表示化と画像の回り込みをすれば良いですかね？

**Comment by mignonstyle** [comment]
@inc2734  ありがとうございます。
スピーカー > Mignon Styleに情報を入れましたので、こちらをテンプレートとしてお使いいただけますか？
https://2017.tokyo.wordcamp.org/speaker/mignonstyle/

・投稿日時、投稿者を非表示に
・SNSの情報がある場合は、スピーカーアイコンの右側に表示（クラス名追加しました）
・「セッション」のところは自動的に挿入されてしまうので、「セッション」を「自己紹介」の見出しと同じに
・セッションタイトルのリンクをblockに
・アイコンは円にしてください（参加者一覧のアイコンが円になってるので統一したいです）

2016年より、2015年のレイアウトを参考にしていただいたほうがよいかもしれません。すみません。
お手数ですが、このような感じでお願い致します。

![2017-08-02 14 26 02](https://user-images.githubusercontent.com/7196028/28858874-c7ea716a-778e-11e7-96c5-febd7f0f0558.png)

**Comment by mignonstyle** [comment]
@inc2734  ありがとうございます！マージンが広くて間延びしてるような感じがするので、全体的にマージンも修正していただけますか？フォントサイズ変えていただいてもよいので。
会社名が入ったときでも、アイコンとのバランスがよくなるようにしていただけると助かります。

![2017-08-03 15 28 39](https://user-images.githubusercontent.com/7196028/28908897-0ed66a5c-7861-11e7-8e70-0a6d739817f4.png)

**Comment by inc2734** [comment]
@mignonstyle 会社名の上、自己紹介見出しの上、セッション見出しの下余白を詰めれば良いですか？

**Comment by mignonstyle** [comment]
@inc2734  ありがとうございます。すみません、サンプル作りましたのこちらでお願いできますか？
![-2017-08-03-17 17 35_01](https://user-images.githubusercontent.com/7196028/28913405-dbd4d370-7872-11e7-85da-1bbb493a2dca.png)

それと、GitHubのアイコンをfa-githubに変更しましたので、お手数ですがcssの修正お願いできますか？（コピペしたらアイコンの種類違ってました。すみません）
![2017-08-03 17 42 05](https://user-images.githubusercontent.com/7196028/28913463-193254c2-7873-11e7-8e81-ce645e3d220a.png)
→ 
![2017-08-03 17 43 23](https://user-images.githubusercontent.com/7196028/28913517-4a5ae71c-7873-11e7-9fcd-7731b754a514.png)

**Comment by mignonstyle** [comment]
@inc2734  修正ありがとうございます！OKですので、こちらはCloseとさせていただきますね！
お手数おかけしました。ありがとうございました。
