### ISSUE TITLE
entry-content にスクロールバーが表示される

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#71]
Issue #64 で overflow-y: visible; を入れていただいた影響かなと思われます。
ご確認よろしくお願い致します。
Macで表示されるのを確認しましたが、Windows(FireFox) でも表示されるようです。

![2017-08-01 0 34 54](https://user-images.githubusercontent.com/7196028/28785420-5efaea56-7651-11e7-880d-19a9c969a676.png)

**Comment by fumikito** [comment]
直ったっぽいのでクローズ。直ってなかったらリオープンしてください
