### ISSUE TITLE
スピーカーのアバターをマウスオーバーすると四角になる

### ISSUE THREAD

**Issue by mekemoke** [wctokyo2017/wct2017#77]
[![Screenshot from Gyazo](https://gyazo.com/bf5e5eda1e6b56e1e16033265ab1903d/raw)](https://gyazo.com/bf5e5eda1e6b56e1e16033265ab1903d)
https://2017.tokyo.wordcamp.org/speaker/megane9988/
↑この画面のアバター部分にマウスオーバーすると再現されます。

**Comment by fumikito** [comment]
@mekemoke 四角になるというか、Gravatarのホバーカードになるので、これは仕様ということで。

![2017-08-08 20 26 08](https://user-images.githubusercontent.com/84587/29069911-e0f93496-7c77-11e7-8b9d-04fc8aac3aa1.png)
