### ISSUE TITLE
スピーカー一覧ページのデザイン修正（スピーカー詳細ページのようにしてください）

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#80]
スピーカー一覧ページをスピーカー詳細ページのようにSNSなどの調整お願いします。

スピーカー一覧ページ
![2017-08-09 14 39 29](https://user-images.githubusercontent.com/7196028/29106570-ad0b2db2-7d10-11e7-8b49-afaf18badb5c.png)

スピーカー詳細ページ
![2017-08-09 14 39 48](https://user-images.githubusercontent.com/7196028/29106580-b897468e-7d10-11e7-8f5e-362b9b1714c3.png)

**Comment by inc2734** [comment]
@mignonstyle 確認お願いします！

**Comment by mignonstyle** [comment]
@inc2734  OKです！ご対応ありがとうございました！
