### ISSUE TITLE
ブログの記事に設定してあるカテゴリからカテゴリページに飛ばない

### ISSUE THREAD

**Issue by mekemoke** [wctokyo2017/wct2017#81]
[![Screenshot from Gyazo](https://gyazo.com/d1537cce3a2d2098dc614c55b372f018/raw)](https://gyazo.com/d1537cce3a2d2098dc614c55b372f018)

一覧やシングルページから、カテゴリーの一覧を見ようとすると404になります。
リンク先がスラッグではなく日本語になっていることが原因のようです。

誤）https://2017.tokyo.wordcamp.org/category/%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B/
正）https://2017.tokyo.wordcamp.org/category/uncategorized/
↑「お知らせ」のスラッグもuncategorizedから変更したほうがいいかも。

**Comment by mignonstyle** [comment]
@mekemoke  修正しましたので、ご確認お願いできますか？問題なければこのIssueをCloseにしてくださいー
