### ISSUE TITLE
ウインドウサイズがせまいとナビメニューの項目が隠れてしまう

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#84]
ウインドウサイズがせまいときにナビメニューの項目が隠れてしまいます。
スマホサイズでないとハンバーガーメニューにならないので、項目にアクセスできません。
お手数ですがご対応よろしくお願い致します。（タブレット以下のサイズはハンバーガーメニューでもよいかなと思いました。）
![2017-08-17 10 41 42](https://user-images.githubusercontent.com/7196028/29392428-cc167b84-8338-11e7-8d90-2d23994050a3.png)

2016年のサイトでは、ちょっとくずれてますが、とりあえず項目は表示されてました。
![2017-08-17 10 43 02](https://user-images.githubusercontent.com/7196028/29392470-fb3b0a4c-8338-11e7-89ef-a3dd2cfb1ff7.png)

**Comment by inc2734** [comment]
@mignonstyle ここは CSS だけで制御しているのではなくて、ウィンドウサイズに応じて HTML が書き換わる仕組みのようです。JS は変更できないので、CSS だけでハンバーガーメニューの切り替えを制御するのは難しいかなと思います。2016みたいに潰してはいるようにしましょうか？

**Comment by mignonstyle** [comment]
@inc2734  ご確認ありがとうございますー。
潰してしまうと文字が読みづらくなってしまうので、PCより狭くなったらカラム落ちするようにしていただいてもよいでしょうか？

使用してるテーマが違いますが、WordCamp US のように、メニューを左詰めでカラム落ちさせるのがきれいだなと思いました。
https://2017.us.wordcamp.org/

![2017-08-24 8 47 30](https://user-images.githubusercontent.com/7196028/29643560-bef99536-88aa-11e7-9080-58fb6c2ad34a.png)

![2017-08-24 8 56 35](https://user-images.githubusercontent.com/7196028/29643563-c434ee56-88aa-11e7-92a7-e10ccaf8c696.png)

**Comment by inc2734** [comment]
@mignonstyle 修正いれました。落とすブレイクポイントはピクセル固定になっているので、メニュー項目が変更になる場合は再調整が必要です。

**Comment by mignonstyle** [comment]
@inc2734  ご対応ありがとうございます！メニュー項目はそのつど私が入れてるので、項目入れるときに気をつけます。
このIssueはCloseとさせていただきますね。
