### ISSUE TITLE
トップページから記事への導線が欲しい

### ISSUE THREAD

**Issue by sysbird** [wctokyo2017/wct2017#85]
記事を書いてもどこかへうもれてしまうのが寂しいです。トップページになにか更新感があると嬉しいです。メニューの「ブログ」では最新記事（ニュース）というのがわからずクリックされにくい気がします。
いまさら難しいのかもしれませんが、これからも記事を書きます、目玉のインタビュー記事など入ると思います、ご検討よろしくですー

**Comment by sysbird** [comment]
あ、すいません、ここへ提案したら？とのことで書いてしまいましたが「primary-sidebar, After-headerとafter-contentsの有効活用」と同じ内容ですね

**Comment by mignonstyle** [comment]
#46 で対応していただきましたので、こちらのIssueはCloseとさせていただきますね！
