### ISSUE TITLE
Gravatar 登録がないスピーカーの画像を表示できるようにする

### ISSUE THREAD

**Issue by naokomc** [wctokyo2017/wct2017#86]
Gravatar がないスピーカーで投稿内に画像がある場合、Mistery Man と、2倍サイズ（192px）の画像が表示されます。

![speaker-headshot](https://user-images.githubusercontent.com/34067/29646984-a020136c-88c1-11e7-9cb0-8a59ba1ad04b.jpg)

他のスピーカーページと整合が取れるようにしてもらえないでしょうか？

手動で画像を挿入したコードはこちらです。必要でしたら変更してください。
https://2017.tokyo.wordcamp.org/wp-admin/post.php?post=3756&action=edit

**Comment by mignonstyle** [comment]
画像の width を設定すればよいので、このIssueはCloseとしますね。
