### ISSUE TITLE
企画物のバナーとリンクを追加してください

### ISSUE THREAD

**Issue by mignonstyle** [wctokyo2017/wct2017#87]
スポンサーバナーの上に企画物のバナーをリンク付きで追加お願いします。
バナー画像はWCTのドライブに入れてあります。
https://drive.google.com/drive/folders/0B7VbzfOyMyxJdF9MbllmWjVNQjQ?usp=sharing

- カルタ https://2017.tokyo.wordcamp.org/lets-enjoy-carta/
- スタンプラリー https://2017.tokyo.wordcamp.org/stamp-rally/
- ブースツアー （記事作成中）

![2017-08-27 18 26 48](https://user-images.githubusercontent.com/7196028/29748688-f4f3c302-8b55-11e7-8b7b-aaa10fa25910.png)

**Comment by fumikito** [comment]
@mignonstyle やりました！
